### ISSUE TITLE
Hello. I am not if its caused by plugman. I wanna be sure if iets not caused by plugman.

### ISSUE THREAD

**Issue by DutchUser** [r-clancy/PlugMan#32]
12.07 19:12:49 [Server] INFO Polski05 issued server command: /plugman reload Statz
12.07 19:12:49 [Server] INFO Disabling Statz v1.1
12.07 19:12:49 [Server] INFO Statz v1.1 has been disabled!
12.07 19:12:49 [Server] WARN org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
12.07 19:12:49 [Server] WARN at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:353)
12.07 19:12:49 [Server] WARN at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:316)
12.07 19:12:49 [Server] WARN at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:377)
12.07 19:12:49 [Server] WARN at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
12.07 19:12:49 [Server] WARN at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
12.07 19:12:49 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
12.07 19:12:49 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
12.07 19:12:49 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
12.07 19:12:49 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1348)
12.07 19:12:49 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1183)
12.07 19:12:49 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
12.07 19:12:49 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
12.07 19:12:49 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
12.07 19:12:49 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
12.07 19:12:49 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
12.07 19:12:49 [Server] WARN at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
12.07 19:12:49 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733)
12.07 19:12:49 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
12.07 19:12:49 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
12.07 19:12:49 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
12.07 19:12:49 [Server] WARN at java.lang.Thread.run(Unknown Source)
12.07 19:12:49 [Server] WARN Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122)
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67)
12.07 19:12:49 [Server] WARN at me.staartvin.statz.Statz.<init>(Statz.java:28)
12.07 19:12:49 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
12.07 19:12:49 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
12.07 19:12:49 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
12.07 19:12:49 [Server] WARN at java.lang.reflect.Constructor.newInstance(Unknown Source)
12.07 19:12:49 [Server] WARN at java.lang.Class.newInstance(Unknown Source)
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
12.07 19:12:49 [Server] WARN ... 22 more
12.07 19:12:49 [Server] WARN Caused by: java.lang.IllegalStateException: Initial initialization
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125)
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67)
12.07 19:12:49 [Server] WARN at me.staartvin.statz.Statz.<init>(Statz.java:28)
12.07 19:12:49 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
12.07 19:12:49 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
12.07 19:12:49 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
12.07 19:12:49 [Server] WARN at java.lang.reflect.Constructor.newInstance(Unknown Source)
12.07 19:12:49 [Server] WARN at java.lang.Class.newInstance(Unknown Source)
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
12.07 19:12:49 [Server] WARN at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:353)
12.07 19:12:49 [Server] WARN at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
12.07 19:12:49 [Server] WARN ... 17 more

**Comment by AnUnknownMiner** [comment]
It **looks** to be caused by Plugman, it seems like there is a false positive happening. 

12.07 19:12:49 [Server] WARN org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!

 Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122)
12.07 19:12:49 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.(JavaPlugin.java:67)
12.07 19:12:49 [Server] WARN at me.staartvin.statz.Statz.(Statz.java:28)

Caused by: java.lang.IllegalStateException: Initial initialization

**Comment by r-clancy** [comment]
I can't seem to re-produce this with the current version of Statz (1.2.1) - can you confirm that this is still happening?

>plugman unload Statz
[15:09:55 INFO]: [Statz] Disabling Statz v1.2.1
[15:09:55 INFO]: [Statz debug] Saving updates to database!
[15:09:55 INFO]: [Statz debug] Save Statz database.
[15:09:55 INFO]: [Statz] Statz v1.2.1 has been disabled!
[15:09:55 INFO]: [PlugMan] Statz has been unloaded.

Sorry for the late response - I've been quite busy as of late.

**Comment by r-clancy** [comment]
@DutchUser 

I can't seem to re-produce this with the latest version of Statz (1.2.1) - can you confirm this is still happening?

>\>plugman reload Statz
[15:15:26 INFO]: [Statz] Disabling Statz v1.2.1
[15:15:26 INFO]: [Statz debug] Saving updates to database!
[15:15:26 INFO]: [Statz debug] Save Statz database.
[15:15:26 INFO]: [Statz] Statz v1.2.1 has been disabled!
[15:15:27 INFO]: [Statz] Enabling Statz v1.2.1
[15:15:27 INFO]: [Statz debug] Using SQLite database!
[15:15:27 INFO]: [Statz debug] ---------------[Statz Dependencies]---------------
[15:15:27 INFO]: [Statz debug] Searching dependencies...
[15:15:27 INFO]: [Statz debug] afkTerminator has not been found!
[15:15:27 INFO]: [Statz debug] Factions has not been found!
[15:15:27 INFO]: [Statz debug] GriefPrevention has not been found!
[15:15:27 INFO]: [Statz debug] UltimateCore has not been found!
[15:15:27 INFO]: [Statz debug] OnTime has not been found!
[15:15:27 INFO]: [Statz debug] mcMMO has not been found!
[15:15:27 INFO]: [Statz debug] Stats has not been found!
[15:15:27 INFO]: [Statz debug] ASkyBlock has not been found!
[15:15:27 INFO]: [Statz debug] Vault has not been found!
[15:15:27 INFO]: [Statz debug] Statistics has not been found!
[15:15:27 INFO]: [Statz debug] Jobs has not been found!
[15:15:27 INFO]: [Statz debug] RoyalCommands has not been found!
[15:15:27 INFO]: [Statz debug] WorldGuard has not been found!
[15:15:27 INFO]: [Statz debug] Essentials has not been found!
[15:15:27 INFO]: [Statz debug] Votifier has not been found!
[15:15:27 INFO]: [Statz debug] AcidIsland has not been found!
[15:15:27 INFO]: [Statz debug] ---------------[Statz Dependencies]---------------
[15:15:27 INFO]: [Statz debug] Loaded libraries and dependencies
[15:15:27 INFO]: [Statz] Statz v1.2.1 has been enabled!
[15:15:27 INFO]: [PlugMan] Statz has been reloaded.
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_players'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_joins'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_deaths'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_items_caught'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_blocks_placed'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_blocks_broken'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_kills_mobs'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_kills_players'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_time_played'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_food_eaten'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_damage_taken'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_times_shorn'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_distance_travelled'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_items_crafted'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_xp_gained'
[15:15:27 INFO]: [Statz debug] Loaded table 'statz_votes'
[15:15:27 INFO]: [Statz debug] Statz is connected to its database!
[15:15:27 INFO]: [Statz debug] Save Statz database.

Sorry for the delayed response - I've been quite busy as of late.

**Comment by DutchUser** [comment]
We are not using StatZ anymore. So i just going close the ticket,
