### ISSUE TITLE
problem with commandbook

### ISSUE THREAD

**Issue by seema84** [r-clancy/PlugMan#37]
spigot 1.11.2
commandbook 2.5-SNAPSHOT
plugman build #8 from 18.12.2016 18:44

i can use unload commandbook and i get a message plugin has been unloaded
but this plugin is unloaded (it works) and i cant load it again
"That file is not a valid Plugin"

/plugman load commandbook
[13:28:08 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
[13:28:08 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
[13:28:08 WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[13:28:08 WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:353)
[13:28:08 WARN]: 	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[13:28:08 WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[13:28:08 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:28:08 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[13:28:08 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:28:08 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:28:08 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[13:28:08 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[13:28:08 WARN]: Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
[13:28:08 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122)
[13:28:08 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67)
[13:28:08 WARN]: 	at com.zachsthings.libcomponents.bukkit.BasePlugin.<init>(BasePlugin.java:44)
[13:28:08 WARN]: 	at com.sk89q.commandbook.CommandBook.<init>(CommandBook.java:75)
[13:28:08 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:28:08 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:28:08 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:28:08 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[13:28:08 WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[13:28:08 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[13:28:08 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[13:28:08 WARN]: 	... 20 more
[13:28:08 WARN]: Caused by: java.lang.IllegalStateException: Initial initialization
[13:28:08 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125)
[13:28:08 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67)
[13:28:08 WARN]: 	at com.zachsthings.libcomponents.bukkit.BasePlugin.<init>(BasePlugin.java:44)
[13:28:08 WARN]: 	at com.sk89q.commandbook.CommandBook.<init>(CommandBook.java:75)
[13:28:08 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:28:08 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:28:08 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:28:08 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[13:28:08 WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[13:28:08 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[13:28:08 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[13:28:08 WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[13:28:08 WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251)
[13:28:08 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204)
[13:28:08 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
[13:28:08 WARN]: 	... 1 more

**Comment by r-clancy** [comment]
The next release should contain a fix for this - 081cf53
