### ISSUE TITLE
Plugin already initialized

### ISSUE THREAD

**Issue by seema84** [r-clancy/PlugMan#38]
/plugman reload essentials
[01:03:23] [Server thread/INFO]: [Essentials] Disabling Essentials v2.0.1-b468
[01:03:23] [Server thread/INFO]: [Vault][Economy] Essentials Economy unhooked.
[01:03:24] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[01:03:24] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:353)
[01:03:24] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:316)
[01:03:24] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:377)
[01:03:24] [Server thread/WARN]: 	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[01:03:24] [Server thread/WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[01:03:24] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:03:24] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[01:03:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[01:03:24] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67)
[01:03:24] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.<init>(Essentials.java:111)
[01:03:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:03:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:03:24] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:03:24] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:03:24] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[01:03:24] [Server thread/WARN]: 	... 22 more
[01:03:24] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Initial initialization
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67)
[01:03:24] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.<init>(Essentials.java:111)
[01:03:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:03:24] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:03:24] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:03:24] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[01:03:24] [Server thread/WARN]: 	at java.lang.Class.newInstance(Class.java:442)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251)
[01:03:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204)
[01:03:24] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
[01:03:24] [Server thread/WARN]: 	... 1 more

**Comment by r-clancy** [comment]
The next release should contain a fix for this - https://github.com/r-clancy/PlugMan/commit/081cf53b8b549f1e17127a44e151b69150a354c3
