### ISSUE TITLE
unfriendly exception thrown when curse is down

### ISSUE THREAD

**Issue by smmmadden** [r-clancy/PlugMan#39]
If there is a hard dependency to curse website for something, we don't need to have such a large traceback. The first two messages are fine. Then provide an option to manually complete the step it was trying to do. Hard to tell here if the server is stable or not when this happens.
[21:11:43 ERROR]: [PlugMan] The updater could not contact dev.bukkit.org for updating.
[21:11:43 ERROR]: [PlugMan] If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.
[21:11:43 ERROR]: [PlugMan] null
java.io.IOException: Server returned HTTP response code: 521 for URL: https://api.curseforge.com/servermods/files?projectIds=36006
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_112]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_112]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_112]
        at net.gravitydevelopment.updater.Updater.read(Updater.java:643) [FirstJoinPlus2.4.1.jar:?]
        at net.gravitydevelopment.updater.Updater.runUpdater(Updater.java:718) [FirstJoinPlus2.4.1.jar:?]
        at net.gravitydevelopment.updater.Updater.access$100(Updater.java:36) [FirstJoinPlus2.4.1.jar:?]
        at net.gravitydevelopment.updater.Updater$UpdateRunnable.run(Updater.java:713) [FirstJoinPlus2.4.1.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
[21:11:43 WARN]: [PlugMan] Updater was unable to connect with dev.bukkit.org to look for updates.

**Comment by r-clancy** [comment]
You're right - no need for the stack trace. It was coming from a library, I've commented out a line and it will be suppressed in the next release.
