### ISSUE TITLE
Problem with /plugman reload <Plugin> Command.

### ISSUE THREAD

**Issue by CatNote** [r-clancy/PlugMan#48]
I entered "reload" command just after start server.
There wasn't error while starting console.

This is my Full log message.

```
[20:03:11] [Server thread/ERROR]: Error occurred while enabling Mirsv v1.12.7.4 (Is it up to date?)
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/mirsv/PluginLists.<clinit>()V @60: invokespecial
  Reason:
    Type 'com/mirsv/moonshine/ItemTag' (current frame, stack[5]) is not assignable to 'com/mirsv/MirPlugin'
  Current Frame:
    bci: @60
    flags: { }
    locals: { }
    stack: { uninitialized 44, uninitialized 44, 'java/lang/String', integer, 'java/lang/String', 'com/mirsv/moonshine/ItemTag' }
  Bytecode:
    0x0000000: bb00 0159 1220 0312 20bb 0021 59b7 0023
    0x0000010: b700 26b3 0029 bb00 0159 122b 0412 2bbb
    0x0000020: 002c 59b7 002e b700 26b3 002f bb00 0159
    0x0000030: 1231 0512 31bb 0032 59b7 0034 b700 26b3
    0x0000040: 0035 bb00 0159 1237 0612 37bb 0038 59b7
    0x0000050: 003a b700 26b3 003b bb00 0159 123d 0712
    0x0000060: 3dbb 003e 59b7 0040 b700 26b3 0041 bb00
    0x0000070: 0159 1243 0812 43bb 0044 59b7 0046 b700
    0x0000080: 26b3 0047 bb00 0159 1249 1006 1249 bb00
    0x0000090: 4a59 b700 4cb7 0026 b300 4dbb 0001 5912
    0x00000a0: 4f10 0712 4fbb 0050 59b7 0052 b700 26b3
    0x00000b0: 0053 bb00 0159 1255 1008 1255 bb00 5659
    0x00000c0: b700 58b7 0026 b300 59bb 0001 5912 5b10
    0x00000d0: 0912 5bbb 005c 59b7 005e b700 26b3 005f
    0x00000e0: bb00 0159 1261 100a 1261 bb00 6259 b700
    0x00000f0: 64b7 0026 b300 65bb 0001 5912 6710 0b12
    0x0000100: 67bb 0068 59b7 006a b700 26b3 006b bb00
    0x0000110: 0159 126d 100c 126d bb00 6e59 b700 70b7
    0x0000120: 0026 b300 71bb 0001 5912 7310 0d12 73bb
    0x0000130: 0074 59b7 0076 b700 26b3 0077 bb00 0159
    0x0000140: 1279 100e 1279 bb00 7a59 b700 7cb7 0026
    0x0000150: b300 7dbb 0001 5912 7f10 0f12 7fbb 0080
    0x0000160: 59b7 0082 b700 26b3 0083 bb00 0159 1285
    0x0000170: 1010 1285 bb00 8659 b700 88b7 0026 b300
    0x0000180: 8910 11bd 0001 5903 b200 2953 5904 b200
    0x0000190: 2f53 5905 b200 3553 5906 b200 3b53 5907
    0x00001a0: b200 4153 5908 b200 4753 5910 06b2 004d
    0x00001b0: 5359 1007 b200 5353 5910 08b2 0059 5359
    0x00001c0: 1009 b200 5f53 5910 0ab2 0065 5359 100b
    0x00001d0: b200 6b53 5910 0cb2 0071 5359 100d b200
    0x00001e0: 7753 5910 0eb2 007d 5359 100f b200 8353
    0x00001f0: 5910 10b2 0089 53b3 008b b1            

	at com.mirsv.Mirsv.InstallPlugins(Mirsv.java:79) ~[Mirsv.jar:?]
	at com.mirsv.Mirsv.onEnable(Mirsv.java:31) ~[Mirsv.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [PaperSpigot-latest.jar:git-Paper-1172]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:666) [PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:629) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:462) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:425) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-latest.jar:git-Paper-1172]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
```

**Comment by CatNote** [comment]
This is one of the method in Mirsv.java.
Line 79 is "PluginLists[] plugin = PluginLists.values();"

public void InstallPlugins() {
		plugins.clear();

		PluginLists[] plugin = PluginLists.values();
		for (PluginLists plu: plugin) {
			if (getConfig().getBoolean("enable." + plu.getPluginName(), true)) {
				plugins.add(ChatColor.GREEN + plu.getPluginName());
				plu.getPlugin();
				getConfig().set("enable." + plu.getPluginName(), true);
			} else {
				plugins.add(ChatColor.RED + plu.getPluginName());
				getConfig().set("enable." + plu.getPluginName(), false);
			}
		}
	}

**Comment by r-clancy** [comment]
This issue doesn't appear to be caused by PlugMan, but rather the plugin you're trying to reload - you'll have to reach out to the developer of that plugin.
