### ISSUE TITLE
/plugman check all

### ISSUE THREAD

**Issue by xbette** [r-clancy/PlugMan#49]
Hello when i run /plugman check all with or without -f it just gives me this error in console

[03:17:40 WARN]: [PlugMan] Plugin PlugMan v2.1.4 generated an exception while executing task 12698603
java.lang.NullPointerException: null
        at com.rylinaux.plugman.util.SpiGetUtil.checkUpToDate(SpiGetUtil.java:89) ~[?:?]
        at com.rylinaux.plugman.util.SpiGetUtil.checkUpToDate(SpiGetUtil.java:67) ~[?:?]
        at com.rylinaux.plugman.command.CheckCommand$1.run(CheckCommand.java:122) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-65e8124-79e55b6]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-65e8124-79e55b6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by carrowood** [comment]
Same experience on git-Spigot-b0f4c22-a2dd0e3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

https://pastebin.com/bzExgT5K

**Comment by r-clancy** [comment]
Should be fixed in 60e08d852cc20a791028f4a98ca0ae69456cfd66 

Give the `master` branch a try or download the pre-built from [here](https://www.dropbox.com/s/805826r12hwtbre/PlugMan.jar?dl=0).
