### ISSUE TITLE
When enabling certain plugins, PlugMan causes the server to crash

### ISSUE THREAD

**Issue by eirikh1996** [r-clancy/PlugMan#52]
When trying to enable certain plugins using plugman, something goes wrong and causes the server to shut down.

[16:40:23] [Server thread/INFO]: eirikh1996 issued server command: /plugman enable FastAsyncWorldEdit
[16:40:23] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v17.12.09-7e3bec1-948-18.0.5
[16:40:23] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader FastAsyncWorldEdit v17.12.09-7e3bec1-948-18.0.5
[16:40:23] [Server thread/WARN]: javax.management.InstanceAlreadyExistsException: FAWE has already been initialized with: com.boydti.fawe.bukkit.FaweBukkit@5387fe51
[16:40:23] [Server thread/WARN]: 	at com.boydti.fawe.Fawe.set(Fawe.java:261)
[16:40:23] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.FaweBukkit.<init>(FaweBukkit.java:101)
[16:40:23] [Server thread/WARN]: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:73)
[16:40:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:40:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[16:40:24] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:40:24] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62)
[16:40:24] [Server thread/WARN]: 	at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127)
[16:40:24] [Server thread/WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[16:40:24] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:40:24] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[16:40:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:674)
[16:40:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1471)
[16:40:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1276)
[16:40:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:40:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:40:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[16:40:24] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:40:24] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[16:40:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[16:40:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[16:40:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[16:40:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[16:40:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[16:40:24] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by CloudeLecaw** [comment]
this is normal for Plugins like AsnyWorldEdit, WorldEdit, Worldgaurd, Pex, Multiverse,  and many other big main Server plugins.
plugman should not used if u plan u update your Major plugins. for this u allways should do a clear restart of your Server ;)
