### ISSUE TITLE
Repeating Error 

### ISSUE THREAD

**Issue by DaDMaR** [r-clancy/PlugMan#56]
[00:23:52 INFO]: This server is running CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

[00:23:53 INFO]: [PlugMan] Loading PlugMan v2.1.4

[12:20:54 WARN]: [PlugMan] Plugin PlugMan v1.8.1 generated an exception while executing task 41
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.ryanclancy000.plugman.utilities.MetricsLite.postPlugin(MetricsLite.java:261) ~[?:?]
	at com.ryanclancy000.plugman.utilities.MetricsLite.access$300(MetricsLite.java:48) ~[?:?]
	at com.ryanclancy000.plugman.utilities.MetricsLite$1.run(MetricsLite.java:153) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

CHANGED config.yml settings as below - stopped error for now

use-metrics: false
skip-on-reload:
- Spout
- dynmap
- Essentials
ignored-plugins:
- PlugMan
update-alerts: false
updater-type: download

**Comment by Dart2112** [comment]
1.8.1 is incredibly old(2012 in fact), for some reason the auto-updater keeps downloading that version in place of the new one. what you need to do is redownload from Bukkit and completely reinstall. remove all plugman files. then reinstall the current version from Bukkit and disable auto updates. then delete the already downloaded update from the update folder. this will allow you to stay on the current stable version.

**Comment by r-clancy** [comment]
Apologies for the delay - I've been travelling for the past 2 months.

The latest version from my Jenkins has the auto-updater removed, please give it a try and let me know how it works.

https://ci.ryan-clancy.com/job/PlugMan/job/master/12/artifact/target/PlugMan.jar
