### ISSUE TITLE
Plugin PlugMan v1.8.1 generated an exception while executing task 27

### ISSUE THREAD

**Issue by C4BR3R4** [r-clancy/PlugMan#58]
Error in console:
```
[Craft Scheduler Thread - 1188/WARN]: [PlugMan] Plugin PlugMan v1.8.1 generated an exception while executing task 27
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at com.ryanclancy000.plugman.utilities.MetricsLite.postPlugin(MetricsLite.java:261) ~[PlugMan.jar:?]
    at com.ryanclancy000.plugman.utilities.MetricsLite.access$300(MetricsLite.java:48) ~[PlugMan.jar:?]
    at com.ryanclancy000.plugman.utilities.MetricsLite$1.run(MetricsLite.java:153) ~[PlugMan.jar:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```
Plugman installed version 2.1.4

**Comment by Dart2112** [comment]
The auto-updater is downloading an old version of the plugin, what you need to do is delete the plugin and its data folder then reinstall the latest version from Bukkit and set auto update to none and then delete the downloaded update from the update folder.

**Comment by r-clancy** [comment]
Apologies for the delay - I've been travelling for the past 2 months.

The latest version from my Jenkins has the auto-updater removed, please give it a try and let me know how it works.

https://ci.ryan-clancy.com/job/PlugMan/job/master/12/artifact/target/PlugMan.jar
