### ISSUE TITLE
 PlugMan v1.8.1 generated an exception while executing task 49

### ISSUE THREAD

**Issue by FilDa196** [r-clancy/PlugMan#62]
`> [07:06:15 WARN]: [PlugMan] Plugin PlugMan v1.8.1 generated an exception while executing task 49
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at com.ryanclancy000.plugman.utilities.MetricsLite.postPlugin(MetricsLite.java:261) ~[PlugMan.jar:?]
at com.ryanclancy000.plugman.utilities.MetricsLite.access$300(MetricsLite.java:48) ~[PlugMan.jar:?]
at com.ryanclancy000.plugman.utilities.MetricsLite$1.run(MetricsLite.java:153) ~[PlugMan.jar:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[paperspigot.jar:git-Paper-1104]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [paperspigot.jar:git-Paper-1104]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [paperspigot.jar:git-Paper-1104]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

**Comment by r-clancy** [comment]
Apologies for the delay - I've been travelling for the past 2 months.

The latest version from my Jenkins has the auto-updater removed, please give it a try and let me know how it works.

https://ci.ryan-clancy.com/job/PlugMan/job/master/12/artifact/target/PlugMan.jar
