### ISSUE TITLE
MaxBans is always using "root" login for MySQL

### ISSUE THREAD

**Issue by plagoutte** [r-clancy/PlugMan#87]
Hello,

I configured MaxBans to use "bans" user to connect to MySQL database, but it is using root (see error bellow).
**config.yml** :
```
database:
   driver: "com.mysql.jdbc.Driver"
   url: "jdbc:mysql://localhost:3306/bans"
   user: "bans"
   password: "**************"
```

**Error** : 
```
[23:55:45 WARN]: [MaxBansPlus] Loaded class com.mysql.cj.jdbc.Driver from SkinsRestorer v13.7.9 which is not a depend, softdepend or loadbefore of this plugin.
[23:55:46 ERROR]: [MaxBansPlus] Unable to migrate database. Disabling MaxBans
org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost:3306/bans) for user 'root': Access denied for user 'root'@'localhost' (using password: YES)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:412) ~[?:?]
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:370) ~[?:?]
        at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50) ~[?:?]
        at org.flywaydb.core.Flyway.execute(Flyway.java:1326) ~[?:?]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:917) ~[?:?]
        at org.maxgamer.maxbans.MaxBansPlus.migrate(MaxBansPlus.java:85) ~[?:?]
        at org.maxgamer.maxbans.MaxBansPlus.onEnable(MaxBansPlus.java:112) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-307]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-307]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-307]
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
        at com.rylinaux.plugman.command.RestartCommand.execute(RestartCommand.java:124) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-307]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:723) ~[patched_1.15.2.jar:git-Paper-307]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Paper-307]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-307]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-307]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:827) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[?:?]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[?:?]
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:409) ~[?:?]
        ... 21 more
[23:55:46 INFO]: [MaxBansPlus] Disabling MaxBansPlus v2.0
```

Thanks in advance
Sincerely

**Comment by Moose1301** [comment]
Recommand not using plugman to load it and try make a report with the people who make maxbans if a server restart doesnt work
